var islandVillage = document.querySelector(".island-details");
var islands = document.querySelectorAll(".island");
let elementToEscape;
const data = [
	[
		"<h3>Tidal Energy</h3>Tidal energy harnesses the kinetic energy of tidal currents. Tidal power plants use underwater turbines to generate electricity as tides flow in and out.",
		"<h3>Wave Energy</h3>Wave energy converters capture the up and down motion of ocean waves. These devices often employ oscillating water columns or point absorbers to convert wave motion into electricity.",
	],
	[
		"<h3>Wind Energy</h3>While not directly extracting energy from the ocean, offshore wind farms positioned in the sea harness the strong and consistent winds over the ocean to generate electricity.",
		"<h3>Solar Farms</h3>Some regions with access to large bodies of water, such as oceans and seas, deploy floating solar panels to generate electricity from both sunlight and the cooling effect of the water.",
	],
	[
		"<h3>Osmotic Power</h3>Osmotic power is generated by the exchange of freshwater and seawater through a semipermeable membrane. The pressure difference drives a turbine, producing electricity",
		"<h3>Hydrokinetic Energy</h3>This method utilises the movement of water due to ocean currents and waves to turn underwater turbines and generate electricity.",
	],
	[
		"<h3>Ocean Current Energy</h3>Underwater turbines or submerged devices are used to capture the kinetic energy of ocean currents, similar to tidal energy but on a larger scale.",
		"<h3>Underwater Kites</h3>These devices resemble underwater kites and are tethered to the seabed. They move in the ocean currents, generating power through the motion of the tether.",
	],
	[
		"<h3>Ocean Thermal Energy Conversion</h3>OTEC systems use the temperature difference between warm surface water and cold deep water to generate power. Heat exchangers and turbines are key components in this process.",
		"<h3>Salinity Gradient Power</h3>Also known as blue energy, this method exploits the difference in salt concentration (salinity) between seawater and freshwater. Membrane-based technologies can be used to generate electricity.",
	],
];
const x = 20;

islands[0].style.top = "100px";
islands[0].style.left = "100px";

islands.forEach((island, index) => {
	island.style.top = 10 * (index + 1) + 2 * x * (index % 2) + "%";
	island.style.left = 5 + x * index + "%";
	island.style.backgroundImage = `url("photos/island${index + 1}.png")`;
});

function ZoomIn(element, index) {
	index %= 2;
	if (element instanceof HTMLDivElement) {
		islands.forEach((island) => {
			island.removeEventListener("click", ZoomIn);
			island.classList.remove("island-hover");
		});
		elementToEscape = islandVillage;
		document.addEventListener("keyup", KeyUp);
		IntroduceIsland(element, index);
	}
}

function IntroduceIsland(element, index) {
	document.getElementById("title").innerHTML =
		element.innerHTML.split("<")[0];
	elementToEscape.style.opacity = "1";
	InsertData(index);
}

function KeyUp(event) {
	if (event.key === "Escape") {
		elementToEscape.style.opacity = "0";
		document.removeEventListener("keyup", KeyUp);
		islands.forEach((island) => {
			island.classList.add("island-hover");
		});
	}
}

function InsertData(index) {
	var data1 = document.getElementById("data1");
	var data2 = document.getElementById("data2");
	data1.innerHTML = data[index][0];
	data2.innerHTML = data[index][1];
}
